name: Build

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest
    container:
      image: docker.io/fedora:latest

    steps:
    - uses: actions/checkout@v3
    - run: bash -c "yum -y install libadwaita cmake gcc"
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: 'stable'
        override: true
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
